version: '3.3'

volumes:
  pg_data:
  static:
  media:
  redoc:

services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: shustrov19/foodgram_backend
    env_file:
      - .env
    volumes:
      - static:/app/static/
      - media:/app/media/
      - redoc:/app/docs/
    depends_on:
      - db

  
  frontend:
    image: shustrov19/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
  
  nginx:
    image: nginx:1.19.3
    ports:
      - "8080:80"
    volumes:
      - static:/var/www/static/
      - media:/var/www/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
