# Generated by Django 4.1 on 2023-09-09 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_auto_20230906_1825"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
