# Generated by Django 4.1 on 2023-09-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_delete_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredientrecipe",
            name="measurement_unit",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Единица измерения"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                upload_to="recipes/images/", verbose_name="Изображение блюда"
            ),
        ),
    ]
