# Generated by Django 4.1 on 2023-09-11 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_ingredientrecipe_measurement_unit_alter_recipe_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredientrecipe",
            name="measurement_unit",
        ),
    ]
