# Generated by Django 4.1 on 2023-09-12 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_remove_ingredientrecipe_measurement_unit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredientrecipe",
            options={
                "verbose_name": "Игредиент для рецепта",
                "verbose_name_plural": "Игредиенты для рецептов",
            },
        ),
        migrations.AlterModelOptions(
            name="tagrecipe",
            options={
                "verbose_name": "Тег для рецепта",
                "verbose_name_plural": "Теги для рецептов",
            },
        ),
        migrations.AlterField(
            model_name="ingredientrecipe",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients_for_recipe",
                to="recipes.ingredient",
                verbose_name="Ингредиент",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredientrecipe",
            constraint=models.UniqueConstraint(
                fields=("ingredient", "recipe"),
                name="Уникальный ингредиент для рецепта",
            ),
        ),
        migrations.AddConstraint(
            model_name="tagrecipe",
            constraint=models.UniqueConstraint(
                fields=("tag", "recipe"), name="Уникальный тег для рецепта"
            ),
        ),
    ]
